apiVersion: apps/v1
kind: Deployment

metadata:
  name: laravel
  namespace: laravel-dev

spec:
  replicas: 2

  selector:
    matchLabels:
      app: laravel

  template:
    metadata:
      labels:
        app: laravel

    spec:

      # ==================================
      # INIT CONTAINER
      # Copy Laravel source ke shared volume
      # ==================================

      initContainers:

        - name: init-laravel

          image: asia-southeast2-docker.pkg.dev/project-56b2f5d2-7168-44bb-ab5/laravel-dev/laravel-app:latest

          command:
            - sh
            - -c
            - |
              cp -a /var/www/html/. /shared/

          volumeMounts:
            - name: laravel-app
              mountPath: /shared


      # ==================================
      # APPLICATION CONTAINERS
      # ==================================

      containers:

        # ==================================
        # NGINX
        # ==================================

        - name: nginx

          image: nginx:1.27-alpine

          ports:
            - containerPort: 80

          volumeMounts:

            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

            - name: laravel-app
              mountPath: /var/www/html


        # ==================================
        # PHP-FPM
        # ==================================

        - name: php-fpm

          image: asia-southeast2-docker.pkg.dev/project-56b2f5d2-7168-44bb-ab5/laravel-dev/laravel-app:latest

          ports:
            - containerPort: 9000

          # ==================================
          # ENVIRONMENT VARIABLES
          # ==================================

          envFrom:

            - configMapRef:
                name: laravel-config

            - secretRef:
                name: laravel-secret

          volumeMounts:

            - name: laravel-app
              mountPath: /var/www/html


      # ==================================
      # VOLUMES
      # ==================================

      volumes:

        - name: nginx-config

          configMap:
            name: nginx-config


        - name: laravel-app

          emptyDir: {}
