apiVersion: v1
kind: Secret

metadata:
  name: laravel-secret
  namespace: laravel-dev

type: Opaque

stringData:
  APP_KEY: "base64:CRTiEsiR72WQgKXZgv6Jrh6P7D9x4zLfrRhCZPk+524="
  DB_USERNAME: "laravel"
  DB_PASSWORD: "@@10laravel10@@"