apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-storage
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: app-volume
          mountPath: /usr/share/nginx/html       
  volumes:
    - name: app-volume
      persistentVolumeClaim:
        claimName: app-storage