apiVersion: v1
kind: Secret
metadata:
  name: gcp-secret-1
type: Opaque
stringData:
  # This is a placeholder for the actual service account JSON content.
  service-account.json: |
    {
      "type": "service_account",
      "project_id": "my-project",
      "private_key_id": "abcd12345",
      "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
      "client_email": "admin@my-project.iam.gserviceaccount.com"
    }