apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
type: Opaque

stringData:
  APP_KEY: "base64:kiDIm+P4zBbzUuK5pZTLzYUvxn+cE88qNXvoPrDoKVs="
  DB_USERNAME: "laravel"
  DB_PASSWORD: "Password123!"